const LEVELS = [
  {
    id: 1,
    story: "Fogoly vagy. Három cellából kell választanod, hogy melyikbe zárjanak.",
    question: "Melyik cellát választod?",
    doors: [
      { label: "A", hint: "🔥 Lángoló cella — tűz emészti", answer: "Tűz által marcangoló halál" },
      { label: "B", hint: "🦁 8 éve éhező oroszlán lakik itt", answer: "Éhes oroszlán vár rád" },
      { label: "C", hint: "⚡ Villamos szék — évek óta használaton kívül", answer: "Régi villamos szék" },
    ],
    correct: 1,
    explanation: "Ha az oroszlán 8 éve nem evett, már rég éhen halt. A B cella üres!",
  },
  {
    id: 2,
    story: "Süllyedő hajón vagy. Három mentőcsónak maradt.",
    question: "Melyik csónakba szállsz?",
    doors: [
      { label: "A", hint: "🦈 Cápainfestált vizeken átkelő csónak", answer: "Cáfák között evezne" },
      { label: "B", hint: "🌊 Érintetlen tengerre indul, de a csónak lyukas", answer: "Lyukas csónak" },
      { label: "C", hint: "🧭 Régi, de ép csónak — a kapitány is ezt választotta", answer: "Biztonságos, ép csónak" },
    ],
    correct: 2,
    explanation: "A lyukas csónak elmerül. A cáfás vizek halálosak. A régi, ép csónak a legjobb esély.",
  },
  {
    id: 3,
    story: "Elveszett vagy egy erdőben. Három ösvény áll előtted.",
    question: "Melyik úton indulsz el?",
    doors: [
      { label: "A", hint: "🐺 Farkasüvöltés hallatszik — friss vér a földön", answer: "Farkasok vadásznak itt" },
      { label: "B", hint: "💀 Koponya figyelmeztető táblák szegélyezik", answer: "Figyelmeztető táblák" },
      { label: "C", hint: "🌿 Csendes, madárcsicsergés — nyomok egy faluhoz vezetnek", answer: "Biztonságos falusi ösvény" },
    ],
    correct: 2,
    explanation: "A madárcsicsergés azt jelzi, hogy nincs közelben ragadozó. A faluba vezető nyomok biztonságot ígérnek.",
  },
  {
    id: 4,
    story: "Egy elhagyatott épületben vagy. Tűz ütött ki. Három kijárat van.",
    question: "Melyik kijáraton mész ki?",
    doors: [
      { label: "A", hint: "🔥 A kilincs forró — tűz van a másik oldalon", answer: "Tűz van mögötte" },
      { label: "B", hint: "💨 Füst szivárog alatta, de a kilincs hideg", answer: "Füst, de a tűz messze van" },
      { label: "C", hint: "🚪 Hideg kilincs, semmi füst, friss levegő érződik", answer: "Szabad kijárat" },
    ],
    correct: 2,
    explanation: "A forró kilincs mögött tűz van. A hideg kilincs és friss levegő jelzi a biztonságos kijáratot.",
  },
  {
    id: 5,
    story: "Sivatagi karaván vagy. Három oázist látsz a távolban.",
    question: "Melyik oázishoz indulsz?",
    doors: [
      { label: "A", hint: "✨ Tükörfényes tavat látsz — táncoló fény a homokon", answer: "Délibáb — nem létező tó" },
      { label: "B", hint: "🌴 Pálmafák, madarak köröznek felette", answer: "Igazi oázis — madarak jelzik" },
      { label: "C", hint: "💀 Csontok hevernek körülötte — előző utazók maradványai", answer: "Mérgezett víz — csontok figyelmeztetnek" },
    ],
    correct: 1,
    explanation: "A délibáb optikai csalódás. A csontok mérgezett vizet jeleznek. A madarak igazi vizet jeleznek.",
  },
  {
    id: 6,
    story: "Zombiapokalipszis. Három épületbe menekülhetsz.",
    question: "Melyikbe bújsz el?",
    doors: [
      { label: "A", hint: "🏥 Kórház — tele sebesültekkel és zombikkal", answer: "Zombik tanyája" },
      { label: "B", hint: "🏪 Szupermarket — készletek, de a bejáratnál csorda vár", answer: "Zombicsorda állja az utat" },
      { label: "C", hint: "🔒 Rendőrőrs — vastag falak, fegyverek, lezárt ablakok", answer: "Megerősített, biztonságos épület" },
    ],
    correct: 2,
    explanation: "A kórház és a szupermarket tele van zombikkal. A rendőrőrs vastag falai és fegyverei nyújtják a legjobb védelmet.",
  },
  {
    id: 7,
    story: "Kalózhajón fogoly vagy. Három lehetőséged van a szökésre.",
    question: "Melyiket választod?",
    doors: [
      { label: "A", hint: "🌊 Ugrás a tengerbe — éjszaka, ismeretlen vizeken", answer: "Cáfák, áramlatok, sötétség" },
      { label: "B", hint: "⚓ Elrejtőzés a raktárban — holnap kikötőbe érnek", answer: "Rejtőzés a kikötőig" },
      { label: "C", hint: "🗡️ Szembe szállás 20 felfegyverzett kalózzal", answer: "20 felfegyverzett kalóz ellen" },
    ],
    correct: 1,
    explanation: "Az éjszakai ugrás halálos. 20 kalóz ellen esélyed sincs. A raktárban elrejtőzve megvárod a kikötőt.",
  },
  {
    id: 8,
    story: "Barlangban rekedsz. Az árvíz közeleg. Három folyosó van.",
    question: "Melyiken futsz?",
    doors: [
      { label: "A", hint: "📉 Lefelé vezet — a víz hangja egyre erősebb", answer: "Lefelé vezet a vízbe" },
      { label: "B", hint: "➡️ Vízszintes — nedves falak, víz csorog", answer: "Vízszintes, elárasztódik" },
      { label: "C", hint: "📈 Felfelé vezet — friss szellő érezhető", answer: "Felfelé, friss levegő a kijáratnál" },
    ],
    correct: 2,
    explanation: "A víz mindig lefelé folyik. A felfelé vezető folyosó friss szellője kijáratot jelent.",
  },
  {
    id: 9,
    story: "Tudós laborban mérgező gáz szivárog. Három helyiségbe menekülhetsz.",
    question: "Hova rohansz?",
    doors: [
      { label: "A", hint: "🧪 Vegyszerraktár — robbanásveszélyes anyagok", answer: "Robbanásveszély" },
      { label: "B", hint: "🌬️ Szellőztető helyiség — légáramlás szívja be a gázt", answer: "A gáz ide áramlik" },
      { label: "C", hint: "🔒 Nyomástartó kamra — hermetikusan lezárt ajtó", answer: "Hermetikusan lezárt, gázmentes" },
    ],
    correct: 2,
    explanation: "A vegyszerraktárban robbanás kockázata áll fenn. A szellőztető szívja be a gázt. A hermetikus kamra kizárja a gázt.",
  },
  {
    id: 10,
    story: "Hegymászás közben lavina indul. Három irány van.",
    question: "Merre futsz?",
    doors: [
      { label: "A", hint: "⬇️ Lefelé a hegyoldalon — a lavina iránya", answer: "A lavina éppen erre zúdul" },
      { label: "B", hint: "➡️ Oldalra, egy szikla mögé — vastag kőfal takar", answer: "Szikla mögé — a lavina elhalad mellette" },
      { label: "C", hint: "⬆️ Felfelé — a lavina forrása felé", answer: "Egyenesen a lavinába rohansz" },
    ],
    correct: 1,
    explanation: "A lavina lefelé zúdul, tehát lefelé futni halálos. Felfelé szintén. A szikla mögé bújva a lavina áthalad feletted.",
  },
  {
    id: 11,
    story: "Egy szigeten vagy. Három csoporthoz csatlakozhatsz.",
    question: "Melyik csoporthoz mégy?",
    doors: [
      { label: "A", hint: "🔪 Felfegyverzett túlélők — de egymást is megtámadják az élelmiszert", answer: "Erőszakos, megbízhatatlan csoport" },
      { label: "B", hint: "🤝 Kis csoport — együttműködnek, van tüzük és menedékük", answer: "Megbízható, szervezett csoport" },
      { label: "C", hint: "😴 Egyedül alszó ember — nem kommunikál senkivel", answer: "Magányos, elszigetelt túlélő" },
    ],
    correct: 1,
    explanation: "Az erőszakos csoport veszélyes. Az egyedüli túlélő nem nyújt segítséget. A szervezett, együttműködő csoport a legjobb esély.",
  },
  {
    id: 12,
    story: "Apokaliptikus városban vagy. Három autó parkol előtted.",
    question: "Melyikkel próbálsz menekülni?",
    doors: [
      { label: "A", hint: "⛽ Sportkocsi — üres a tank, kulcs bent van", answer: "Üres tankkal sehova sem jutni" },
      { label: "B", hint: "🚗 Öreg terepjáró — teli tank, kulcs a napon", answer: "Teli tank, megbízható terepjáró" },
      { label: "C", hint: "🏎️ Luxusautó — teli tank, de defektes mindkét kereke", answer: "Defektes kerekekkel nem megy" },
    ],
    correct: 1,
    explanation: "A sportkocsival üres tankkal nem jutsz sehova. A luxusautó defektes. A terepjáró teli tankkal és ép kerekekkel a nyerő.",
  },
  {
    id: 13,
    story: "Dzsungelben vagy. Három folyón kell átkelned.",
    question: "Melyiken kelsz át?",
    doors: [
      { label: "A", hint: "🐊 Nyugodt víz — de krokodilfejek látszanak a felszínen", answer: "Krokodiloktól hemzseg" },
      { label: "B", hint: "💧 Sebes sodrású folyó — de sekély, látnod a köveket", answer: "Sebes, de sekély és átgázolható" },
      { label: "C", hint: "🌿 Sűrű vegetáció takarja — nem látni mi van a vízben", answer: "Ismeretlen veszélyek rejtőznek" },
    ],
    correct: 1,
    explanation: "A krokodilos folyó halálos. Az ismeretlen folyó kiszámíthatatlan. A sekély, sebes folyón köveken át biztonságosan átgázolhatsz.",
  },
  {
    id: 14,
    story: "Posztapokaliptikus bunkerben vagy. Az élelmiszer fogytán. Három irányba indulhatsz.",
    question: "Merre mész élelemért?",
    doors: [
      { label: "A", hint: "☢️ Bevásárlóközpont — de sugárzásveszélyes zónában van", answer: "Sugárzás — lassú halál" },
      { label: "B", hint: "🌱 Mezőgazdasági terület — más túlélők már gondozzák, cserekereskedelem folyik", answer: "Biztonságos csere lehetséges" },
      { label: "C", hint: "🏚️ Elhagyatott raktár — ismeretlen bandák jelölték meg", answer: "Bandaterület — veszélyes" },
    ],
    correct: 1,
    explanation: "A sugárzás lassan öl. A banda jelölte raktár halálos csapda. A gondozott farm ahol csere folyik biztonságos és fenntartható.",
  },
  {
    id: 15,
    story: "Vihar közeleg. Három menedék van közelben.",
    question: "Hova bújsz?",
    doors: [
      { label: "A", hint: "🌳 Nagy fa alatt — villámhárítóként működik viharban", answer: "Villám csaphat a fába" },
      { label: "B", hint: "🚗 Fémautóban — a Faraday-ketrecként véd a villámtól", answer: "Autó Faraday-ketrec — villám ellen véd" },
      { label: "C", hint: "⛺ Nyílt mezőn felvert sátor — legmagasabb pont a környéken", answer: "Legmagasabb pont — villám célpontja" },
    ],
    correct: 1,
    explanation: "A fa villámhárítóként vonzza a villámot. A nyílt sátor a legmagasabb pont. Az autó fémkarosszériája Faraday-ketrecként véd — ez a legbiztonságosabb.",
  },
];

const MAX_LIVES = 3;
const POINTS_PER_CORRECT = 100;
const POINTS_BONUS_STREAK = 50;
