const CATEGORIES = {
  allatok:   "🐾 Állatok",
  etelek:    "🍽️ Ételek",
  varosok:   "🏙️ Városok",
  sport:     "⚽ Sport",
  termeszet: "🌿 Természet",
  targyak:   "🔧 Tárgyak",
};

const WORDS = {
  allatok: [
    { word: "OROSZLÁN",  hint: "Az afrikai szavanna királya" },
    { word: "ELEFÁNT",   hint: "A világ legnagyobb szárazföldi állata" },
    { word: "ZSIRÁF",    hint: "A világ legmagasabb állata" },
    { word: "PINGVIN",   hint: "Fekete-fehér madár, nem tud repülni" },
    { word: "TIGRIS",    hint: "Csíkos nagymacska" },
    { word: "GEPÁRD",    hint: "A leggyorsabb szárazföldi állat" },
    { word: "KOALA",     hint: "Eukaliptuszleveleket eszik" },
    { word: "GORILLA",   hint: "Nagy főemlős, az ember rokona" },
    { word: "DELFIN",    hint: "Okos tengeri emlős" },
    { word: "KROKODIL",  hint: "Veszélyes hüllő, folyókban él" },
    { word: "STRUCC",    hint: "A világ legnagyobb madara, nem repül" },
    { word: "PINGVIN",   hint: "Antarktiszon él, fekete-fehér" },
    { word: "MEDVE",     hint: "Télen hibernál, mézet szeret" },
    { word: "FARKAS",    hint: "Falkában vadász, üvölt a holdra" },
    { word: "LEOPÁRD",   hint: "Foltos nagymacska, fára mászik" },
  ],
  etelek: [
    { word: "PIZZA",      hint: "Olasz kerek lepény sajttal" },
    { word: "HAMBURGER",  hint: "Zsemle között húspogácsa" },
    { word: "SUSHI",      hint: "Japán étel nyers hallal" },
    { word: "GULYÁS",     hint: "Magyar húsleves paprikával" },
    { word: "LÁNGOS",     hint: "Magyar utcai étel, olajban sütve" },
    { word: "PALACSINTA", hint: "Vékony tészta lekvárral vagy Nutellával" },
    { word: "KÜRTŐSKALÁCS", hint: "Magyar édesség, rúdra tekerve sütik" },
    { word: "FAGYLALT",   hint: "Fagyasztott édes desszert" },
    { word: "TIRAMISU",   hint: "Olasz kávés desszert mascarpone-val" },
    { word: "RÁNTOTTA",   hint: "Reggeli tojásos étel serpenyőben" },
    { word: "TÖLTÖTTKÁPOSZTA", hint: "Magyar étel, húsos töltelék káposztalevélbe göngyölve" },
    { word: "RÉTES",      hint: "Magyar sütemény nyújtott tésztával" },
  ],
  varosok: [
    { word: "BUDAPEST",   hint: "Magyarország fővárosa" },
    { word: "PÁRIZS",     hint: "Francia főváros, Eiffel-toronnyal" },
    { word: "LONDON",     hint: "Brit főváros, Big Ben" },
    { word: "TOKIÓ",      hint: "Japán fővárosa" },
    { word: "RÓMA",       hint: "Olasz főváros, az örök város" },
    { word: "MOSZKVA",    hint: "Oroszország fővárosa" },
    { word: "BERLIN",     hint: "Németország fővárosa" },
    { word: "MADRID",     hint: "Spanyolország fővárosa" },
    { word: "PEKING",     hint: "Kína fővárosa" },
    { word: "SYDNEY",     hint: "Ausztrália legnagyobb városa" },
    { word: "DEBRECEN",   hint: "Magyarország második legnagyobb városa" },
    { word: "PÉCS",       hint: "Magyar város, UNESCO örökség" },
    { word: "EGER",       hint: "Magyar város, borvidék, vár" },
  ],
  sport: [
    { word: "FOCI",       hint: "A világ legnépszerűbb csapatsportja" },
    { word: "KOSÁRLABDA", hint: "Kosárba kell dobni a labdát" },
    { word: "TENISZ",     hint: "Ütővel játsszák, hálón át" },
    { word: "ÚSZÁS",      hint: "Vízben végzett sport" },
    { word: "BIRKÓZÁS",   hint: "Két versenyző küzd egymással" },
    { word: "KAJAK",      hint: "Evezős vízi sport" },
    { word: "VÍVÁS",      hint: "Karddal vagy tőrrel folytatott párbaj" },
    { word: "ATLÉTIKA",   hint: "Futás, ugrás, dobás sportja" },
    { word: "KERÉKPÁR",   hint: "Két kerekű jármű, sportág is" },
    { word: "RÖPLABDA",   hint: "Háló felett ütik a labdát" },
    { word: "JÉGKORONG",  hint: "Jégen játsszák, korong a labda" },
    { word: "KÉZILABDA",  hint: "Magyar sikersport, kézzel dobják" },
  ],
  termeszet: [
    { word: "VULKÁN",     hint: "Tűzhányó hegy, lávát lövell" },
    { word: "SZIVÁRÁNY",  hint: "Eső után színes ív az égen" },
    { word: "GLECCSER",   hint: "Lassan mozgó jégtömeg" },
    { word: "VÍZESÉS",    hint: "Szikláról lezúduló víz" },
    { word: "TORNÁDÓ",    hint: "Örvénylő szélvihar" },
    { word: "CUNAMI",     hint: "Óriási tenger hullám" },
    { word: "AURORA",     hint: "Sarki fény az éjszakai égen" },
    { word: "SIVATAG",    hint: "Forró, homokos vidék, kevés csapadék" },
    { word: "DZSUNGEL",   hint: "Sűrű trópusi erdő" },
    { word: "FJORD",      hint: "Norvég tengerparti sziklás öböl" },
  ],
  targyak: [
    { word: "GITÁR",      hint: "Húros hangszer, pengetik" },
    { word: "IRÁNYTŰ",    hint: "Mindig észak felé mutat" },
    { word: "TÁVCSŐ",     hint: "Messze lévő dolgokat mutat nagyítva" },
    { word: "HEGEDŰ",     hint: "Vonós hangszer" },
    { word: "MIKROSZKÓP", hint: "Apró dolgokat láthatóvá tesz" },
    { word: "PERISCOPE",  hint: "Tengeralattjáró megfigyelő eszköze" },
    { word: "SZEXTÁNS",   hint: "Hajósok navigációs eszköze" },
    { word: "METRONOM",   hint: "Zenészek ritmusjelző eszköze" },
    { word: "ABAKUSZ",    hint: "Régi számolóeszköz golyókkal" },
    { word: "KVADRÁNS",   hint: "Csillagászati szögmérő eszköz" },
  ],
};

const MAX_WRONG = 6; // 6 téves tipp = akasztva
