const CATEGORIES = {
  allatok:   "🐾 Állatok",
  etelek:    "🍽️ Ételek",
  varosok:   "🏙️ Városok",
  sport:     "⚽ Sport",
  termeszet: "🌿 Természet",
  targyak:   "🔧 Tárgyak",
};

const DIFFICULTY = {
  easy:   { label: "🟢 Könnyű",  xp: 1 },
  medium: { label: "🟡 Közepes", xp: 2 },
  hard:   { label: "🔴 Nehéz",   xp: 4 },
};

// KÖNNYŰ szavak — rövid, közismert
const WORDS_EASY = {
  allatok: [
    { word: "KUTYA",    hint: "Háziállat, az ember legjobb barátja" },
    { word: "MACSKA",   hint: "Doromboló háziállat" },
    { word: "LÓ",       hint: "Nagy sörényes állat, lovagolnak rajta" },
    { word: "TEHÉN",    hint: "Tejet ad, réten legel" },
    { word: "DISZNÓ",   hint: "Rózsaszín, röfög" },
    { word: "CSIRKE",   hint: "Kotkodál, tojást tojik" },
    { word: "KACSA",    hint: "Hápog, vízben úszik" },
    { word: "NYÚL",     hint: "Hosszú fülű, ugráló állat" },
    { word: "EGÉR",     hint: "Kis rágcsáló, sajtot szeret" },
    { word: "BÉKA",     hint: "Brekeg, vízben él" },
    { word: "MEDVE",    hint: "Nagy barna állat, télen alszik" },
    { word: "FARKAS",   hint: "Üvölt a holdra, falkában vadász" },
    { word: "RÓKA",     hint: "Vörös ravasz állat" },
    { word: "OROSZLÁN", hint: "Az afrikai szavanna királya" },
    { word: "TIGRIS",   hint: "Csíkos nagymacska" },
    { word: "ELEFÁNT",  hint: "Nagy állat, hosszú ormány" },
    { word: "ZSIRÁF",   hint: "Hosszú nyakú legmagasabb állat" },
    { word: "MAJOM",    hint: "Fán lakó főemlős" },
    { word: "PINGVIN",  hint: "Fekete-fehér, nem repül" },
    { word: "DELFIN",   hint: "Okos tengeri emlős" },
    { word: "CÁPA",     hint: "Félelmetes tengeri ragadozó" },
    { word: "KÍGYÓ",    hint: "Lábatlan csúszó hüllő" },
    { word: "TEKNŐS",   hint: "Páncélos lassan mozgó állat" },
    { word: "BAGOLY",   hint: "Éjszakai madár, forgatja a fejét" },
    { word: "SÓLYOM",   hint: "Gyors ragadozó madár" },
    { word: "PAPAGÁJ",  hint: "Trópusi madár, utánoz" },
    { word: "STRUCC",   hint: "Legnagyobb madár, nem repül" },
    { word: "FLAMINGÓ", hint: "Rózsaszín madár, egy lábon áll" },
    { word: "KROKODIL", hint: "Veszélyes folyami hüllő" },
    { word: "GEPÁRD",   hint: "A leggyorsabb szárazföldi állat" },
  ],
  etelek: [
    { word: "ALMA",      hint: "Piros vagy zöld gyümölcs" },
    { word: "KENYÉR",    hint: "Mindennapi sütési alapétel" },
    { word: "PIZZA",     hint: "Olasz kerek lepény sajttal" },
    { word: "TÉSZTA",    hint: "Lisztből készült főzött étel" },
    { word: "LEVES",     hint: "Forró folyékony étel" },
    { word: "SALÁTA",    hint: "Nyers zöldségek keveréke" },
    { word: "FAGYLALT",  hint: "Fagyasztott édes desszert" },
    { word: "TORTA",     hint: "Születésnapi édes sütemény" },
    { word: "RÉTES",     hint: "Magyar nyújtott tésztás sütemény" },
    { word: "LÁNGOS",    hint: "Magyar utcai étel, olajban sütve" },
    { word: "GULYÁS",    hint: "Magyar fűszeres húsleves" },
    { word: "PALACSINTA",hint: "Vékony tészta lekvárral" },
    { word: "HAMBURGER", hint: "Zsemle között húspogácsa" },
    { word: "HOT DOG",   hint: "Virslis hosszú zsemle" },
    { word: "SZENDVICS", hint: "Két szelet kenyér között töltelék" },
    { word: "OMLETT",    hint: "Serpenyőben sütött tojás" },
    { word: "RÁNTOTTA",  hint: "Felvert tojásból készült reggeli" },
    { word: "GOFRI",     hint: "Rácsolt mintás édes sütemény" },
    { word: "PISKÓTA",   hint: "Könnyű tojásos sütemény alap" },
    { word: "KIFLI",     hint: "Félhold alakú péksütemény" },
    { word: "ZSÖMLE",    hint: "Kerek kis péksütemény" },
    { word: "KOLBÁSZ",   hint: "Fűszeres húsból töltött étel" },
    { word: "SZALÁMI",   hint: "Szárított fűszeres húsáru" },
    { word: "SAJT",      hint: "Tejből készült sárga étel" },
    { word: "VAJ",       hint: "Tejszínből készült sárga kenőcs" },
    { word: "TEJFÖL",    hint: "Savanyú tejes sűrű mártás" },
    { word: "JOGHURT",   hint: "Fermentált tejes desszert" },
    { word: "MÉZ",       hint: "Méhek által készített édes szirup" },
    { word: "LEKVÁR",    hint: "Főzött gyümölcsből készült kenőcs" },
    { word: "CSOKI",     hint: "Kakaóból készült édes édesség" },
  ],
  varosok: [
    { word: "BUDAPEST",  hint: "Magyarország fővárosa" },
    { word: "PÁRIZS",    hint: "Eiffel-toronnyal rendelkező főváros" },
    { word: "LONDON",    hint: "Big Ben, brit főváros" },
    { word: "RÓMA",      hint: "Az örök város, Olaszország" },
    { word: "BERLIN",    hint: "Németország fővárosa" },
    { word: "MADRID",    hint: "Spanyolország fővárosa" },
    { word: "BÉCS",      hint: "Osztrák főváros, zene városa" },
    { word: "PRÁGA",     hint: "Csehország fővárosa" },
    { word: "VARSÓ",     hint: "Lengyelország fővárosa" },
    { word: "MOSZKVA",   hint: "Oroszország fővárosa" },
    { word: "TOKIÓ",     hint: "Japán fővárosa" },
    { word: "PEKING",    hint: "Kína fővárosa" },
    { word: "DELHI",     hint: "India fővárosa" },
    { word: "DUBAI",     hint: "Felhőkarcolók városa az UAE-ban" },
    { word: "SYDNEY",    hint: "Ausztrália legnagyobb városa" },
    { word: "NEW YORK",  hint: "Az USA legnagyobb városa" },
    { word: "CHICAGO",   hint: "A szél városa, USA" },
    { word: "MIAMI",     hint: "Floridai tengerparti város" },
    { word: "DEBRECEN",  hint: "Magyarország második legnagyobb városa" },
    { word: "PÉCS",      hint: "Dél-magyarországi kulturális város" },
    { word: "EGER",      hint: "Magyar borvidéki váras" },
    { word: "GYŐR",      hint: "Dunántúli magyar város" },
    { word: "MISKOLC",   hint: "Észak-magyarországi ipari város" },
    { word: "ATHÉN",     hint: "Görögország fővárosa" },
    { word: "LISSZABON", hint: "Portugália fővárosa" },
    { word: "AMSZTERDAM",hint: "Holland főváros, csatornák" },
    { word: "BRÜSSZEL",  hint: "Belgium és EU fővárosa" },
    { word: "STOCKHOLM", hint: "Svédország fővárosa" },
    { word: "OSLO",      hint: "Norvégia fővárosa" },
    { word: "HELSINKI",  hint: "Finnország fővárosa" },
  ],
  sport: [
    { word: "FOCI",        hint: "A világ legnépszerűbb sportja" },
    { word: "TENISZ",      hint: "Ütővel hálón át ütik a labdát" },
    { word: "ÚSZÁS",       hint: "Vízben végzett sport" },
    { word: "FUTÁS",       hint: "Gyalog gyors mozgás" },
    { word: "GOLF",        hint: "Lyukba kell ütni a labdát" },
    { word: "BOKSZ",       hint: "Ökölharcot jelent" },
    { word: "JUDO",        hint: "Japán küzdősport" },
    { word: "KARATE",      hint: "Japán harcművészet" },
    { word: "SÍTALPAS",    hint: "Havon léceken csúszás" },
    { word: "TORNA",       hint: "Akrobatikus ügyességi sport" },
    { word: "RÖPLABDA",    hint: "Háló felett ütik a labdát" },
    { word: "KOSÁR",       hint: "Kosárba kell dobni a labdát" },
    { word: "VÍVÁS",       hint: "Kardos párbaj sport" },
    { word: "EVEZÉS",      hint: "Csónakon lapáttal hajtás" },
    { word: "KAJAK",       hint: "Evezős vízi sport" },
    { word: "ÍJÁSZAT",     hint: "Nyíllal célba lövés" },
    { word: "ATLÉTIKA",    hint: "Futás, ugrás, dobás" },
    { word: "TRIATLON",    hint: "Úszás, kerékpár, futás" },
    { word: "SNOWBOARD",   hint: "Hódeszkázás lejtőn" },
    { word: "CURLING",     hint: "Jégen köveket csúsztatnak söprűkkel" },
    { word: "DARTS",       hint: "Nyilat dobnak céltáblára" },
    { word: "BOWLING",     hint: "Golyóval bábokat döntik" },
    { word: "RÖGBI",       hint: "Ovális labdás brit csapatsport" },
    { word: "KÉZILABDA",   hint: "Magyar sikersport" },
    { word: "VÍZILABDA",   hint: "Vízben játszott labdajáték" },
    { word: "TOLLASLABDA", hint: "Tollasokat ütik hálón át" },
    { word: "BIRKÓZÁS",    hint: "Két versenyző küzd egymással" },
    { word: "MARATONFUTÁS",hint: "42 km-es hosszútávfutás" },
    { word: "KERÉKPÁR",    hint: "Két kerekű jármű, sportág is" },
    { word: "LOVAGLÁS",    hint: "Lóháton versenyeznek" },
  ],
  termeszet: [
    { word: "HEGY",       hint: "Magas kiemelkedés a földön" },
    { word: "VÖLGY",      hint: "Hegyek közötti mélyedés" },
    { word: "TÓ",         hint: "Álló belvíz" },
    { word: "FOLYÓ",      hint: "Folyamatosan áramló víz" },
    { word: "TENGER",     hint: "Nagy sós vízfelület" },
    { word: "ERDŐ",       hint: "Sok fából álló terület" },
    { word: "RÉT",        hint: "Füves síkság" },
    { word: "SIVATAG",    hint: "Forró, homokos száraz vidék" },
    { word: "VULKÁN",     hint: "Tűzhányó, lávát lövell" },
    { word: "SZIGET",     hint: "Vízzel körülvett szárazföld" },
    { word: "SZIKLA",     hint: "Kemény kőzet" },
    { word: "BARLANG",    hint: "Sziklában lévő üreg" },
    { word: "VÍZESÉS",    hint: "Szikláról lezúduló víz" },
    { word: "SZIVÁRÁNY",  hint: "Eső után színes ív az égen" },
    { word: "TORNÁDÓ",    hint: "Örvénylő szélvihar" },
    { word: "VILLÁM",     hint: "Viharban elektromos kisülés" },
    { word: "ESŐ",        hint: "Vízcseppek esnek az égből" },
    { word: "HÓ",         hint: "Fehér téli csapadék" },
    { word: "JÉGESŐ",     hint: "Jégszemeket tartalmazó csapadék" },
    { word: "KÖD",        hint: "Talajszintű vízpára felhő" },
    { word: "SZÉL",       hint: "Légmozgás" },
    { word: "NAPSÜTÉS",   hint: "A Nap sugarai megvilágítják a Földet" },
    { word: "FELHŐ",      hint: "Vízpárából álló légköri képződmény" },
    { word: "HOMOK",      hint: "Apró kőzetszemcsék" },
    { word: "KŐ",         hint: "Szilárd ásványi anyag" },
    { word: "FÖLD",       hint: "Termékeny talaj" },
    { word: "FA",         hint: "Erdőkben élő növény" },
    { word: "VIRÁG",      hint: "Szép színes növényi rész" },
    { word: "FŰSZÁL",     hint: "Apró zöld réti növény" },
    { word: "MOHA",       hint: "Sziklán élő puha növény" },
  ],
  targyak: [
    { word: "SZÉK",       hint: "Ülőbútor" },
    { word: "ASZTAL",     hint: "Lábas lapos bútor" },
    { word: "ÁGY",        hint: "Alvóbútor" },
    { word: "AJTÓ",       hint: "Helyiségbe vezető nyílás" },
    { word: "ABLAK",      hint: "Falba épített üveges nyílás" },
    { word: "LÁMPA",      hint: "Fényt ad" },
    { word: "TÜKÖR",      hint: "Visszaveri a képet" },
    { word: "KÖNYV",      hint: "Olvasni való lapok gyűjteménye" },
    { word: "CERUZA",     hint: "Írásra és rajzolásra" },
    { word: "TOLL",       hint: "Tintával ír" },
    { word: "RADÍR",      hint: "Ceruzát töröl" },
    { word: "OLLÓ",       hint: "Két pengéjű vágóeszköz" },
    { word: "RAGASZTÓ",   hint: "Tárgyakat egymáshoz rögzít" },
    { word: "KALAPÁCS",   hint: "Szöget ver be" },
    { word: "FŰRÉSZ",     hint: "Fát vág" },
    { word: "KULCS",      hint: "Zárat nyit" },
    { word: "ÓRA",        hint: "Időt mutat" },
    { word: "TELEFON",    hint: "Kommunikációs eszköz" },
    { word: "KAMERA",     hint: "Képeket rögzít" },
    { word: "GITÁR",      hint: "Húros hangszer" },
    { word: "ZONGORA",    hint: "Billentyűs hangszer" },
    { word: "DOB",        hint: "Ütős hangszer" },
    { word: "FURULYA",    hint: "Fúvós hangszer" },
    { word: "HEGEDŰ",     hint: "Vonós hangszer" },
    { word: "ESERNYŐ",    hint: "Eső ellen véd" },
    { word: "TÁSKA",      hint: "Dolgokat cipel benne" },
    { word: "HÁTIZSÁK",   hint: "Hátán viselt táska" },
    { word: "CIPŐ",       hint: "Lábbelivéd" },
    { word: "SAPKA",      hint: "Fejet meleg tartó viselet" },
    { word: "KESZTYŰ",    hint: "Kezet meleg tartó viselet" },
  ],
};

// KÖZEPES szavak
const WORDS_MEDIUM = {
  allatok: [
    { word: "GEPÁRD",     hint: "A leggyorsabb szárazföldi állat" },
    { word: "KOALA",      hint: "Eukaliptuszleveleket eszik" },
    { word: "GORILLA",    hint: "Nagy főemlős, az ember rokona" },
    { word: "DELFIN",     hint: "Okos tengeri emlős" },
    { word: "KROKODIL",   hint: "Veszélyes folyami hüllő" },
    { word: "FLAMINGÓ",   hint: "Rózsaszín madár, egy lábon áll" },
    { word: "PELIKÁN",    hint: "Nagy zacskós torkú madár" },
    { word: "KAMÉLEON",   hint: "Hüllő, ami színt vált" },
    { word: "ANACONDA",   hint: "A világ legnagyobb kígyója" },
    { word: "ALLIGÁTOR",  hint: "Krokodil rokona, Amerikában él" },
    { word: "MANGUSZTA",  hint: "Kígyókat eszik" },
    { word: "TAPÍR",      hint: "Kis ormányos állat" },
    { word: "LAJHÁR",     hint: "Lassan mozgó fán lakó állat" },
    { word: "HANGYÁSZ",   hint: "Hosszú orrával hangyákat eszik" },
    { word: "KENGURU",    hint: "Ugró ausztrál erszényes" },
    { word: "PLATIPUSZ",  hint: "Csőrös tojást tojó emlős" },
    { word: "HIÚZ",       hint: "Bojtos fülű vad macska" },
    { word: "GÖRÉNY",     hint: "Büdös menyétféle" },
    { word: "DENEVÉR",    hint: "Az egyetlen repülő emlős" },
    { word: "VAKOND",     hint: "Föld alatt él, alagutat ás" },
    { word: "MORSA",      hint: "Agyaras tengeri emlős" },
    { word: "DUGONG",     hint: "Tengeri tehén, növényevő" },
    { word: "BÁLNA",      hint: "A világ legnagyobb állata" },
    { word: "POLIP",      hint: "Nyolc karú tengeri állat" },
    { word: "MEDÚZA",     hint: "Átlátszó tengeri állat, csíp" },
    { word: "HOMÁR",      hint: "Piros tengeri rák, ollói vannak" },
    { word: "STRUCC",     hint: "A világ legnagyobb madara" },
    { word: "LEOPÁRD",    hint: "Foltos nagymacska, fára mászik" },
    { word: "HIÉNA",      hint: "Dögevő afrikai állat" },
    { word: "VÍZILÓ",     hint: "Nagy afrikai emlős, vízben él" },
  ],
  etelek: [
    { word: "TIRAMISU",    hint: "Olasz kávés desszert" },
    { word: "SUSHI",       hint: "Japán étel nyers hallal" },
    { word: "PAELLA",      hint: "Spanyol rizses tengeri étel" },
    { word: "RATATOUILLE", hint: "Francia zöldséges étel" },
    { word: "FONDUE",      hint: "Svájci olvasztott sajtos mártogatós" },
    { word: "SCHNITZEL",   hint: "Rántott hús, osztrák étel" },
    { word: "GYROS",       hint: "Görög húsos lepényes étel" },
    { word: "HUMMUS",      hint: "Arab csicseriborsókrém" },
    { word: "FALAFEL",     hint: "Sült csicseriborsógolyó" },
    { word: "SHAWARMA",    hint: "Forgó nyársas húsos étel" },
    { word: "PAD THAI",    hint: "Thai pirított tészta étel" },
    { word: "RAMEN",       hint: "Japán húsleveses tészta" },
    { word: "CURRY",       hint: "Indiai fűszeres szósz" },
    { word: "LASAGNE",     hint: "Olasz rétegelt tészta" },
    { word: "RISOTTO",     hint: "Olasz krémes rizs étel" },
    { word: "CARBONARA",   hint: "Olasz tészta tojással szalonnával" },
    { word: "CANNOLI",     hint: "Szicíliai töltött csőstészta" },
    { word: "BAKLAVA",     hint: "Török mézes diós rétes" },
    { word: "PIEROGI",     hint: "Lengyel töltött tészta" },
    { word: "BORSCS",      hint: "Orosz céklaleves" },
    { word: "STROGANOFF",  hint: "Orosz tejfölös marhahús étel" },
    { word: "CEVICHE",     hint: "Latin nyers hal citromlével" },
    { word: "EMPANADA",    hint: "Latin-amerikai töltött tészta" },
    { word: "TAGINE",      hint: "Marokkói agyagedényes étel" },
    { word: "COUSCOUS",    hint: "Észak-afrikai búzadara" },
    { word: "SHAKSHUKA",   hint: "Izraeli tojásos paradicsomos étel" },
    { word: "PHO",         hint: "Vietnami marhahúsleves tésztával" },
    { word: "KIMCHI",      hint: "Koreai fermentált káposzta" },
    { word: "BIBIMBAP",    hint: "Koreai vegyes rizses tál" },
    { word: "MOCHI",       hint: "Japán rizstészta édesség" },
  ],
  varosok: [
    { word: "BARCELONA",    hint: "Spanyol katalán város, Gaudí" },
    { word: "MILÁNÓ",       hint: "Olasz divat és gazdasági főváros" },
    { word: "VELENCE",      hint: "Vízen álló olasz város" },
    { word: "FIRENZE",      hint: "Reneszánsz olasz város" },
    { word: "ISZTAMBUL",    hint: "Két kontinensen lévő török város" },
    { word: "KAIRÓ",        hint: "Egyiptom fővárosa, piramisok" },
    { word: "NAIROBI",      hint: "Kenya fővárosa" },
    { word: "MUMBAI",       hint: "India pénzügyi fővárosa" },
    { word: "BANGALORE",    hint: "India technológiai fővárosa" },
    { word: "BANGKOK",      hint: "Thaiföld fővárosa" },
    { word: "SZINGAPÚR",    hint: "Városállam Délkelet-Ázsiában" },
    { word: "BUENOS AIRES", hint: "Argentína fővárosa" },
    { word: "RIO DE JANEIRO",hint: "Karneváljáról ismert brazil város" },
    { word: "TORONTO",      hint: "Kanada legnagyobb városa" },
    { word: "VANCOUVER",    hint: "Kanadai csendes-óceáni város" },
    { word: "LOS ANGELES",  hint: "Hollywood városa" },
    { word: "SAN FRANCISCO",hint: "Arany kapu hídja van" },
    { word: "AMSTERDAM",    hint: "Holland főváros, csatornák" },
    { word: "BUDAPEST",     hint: "Magyarország fővárosa a Duna mellett" },
    { word: "KOPPENHÁGA",   hint: "Dánia fővárosa" },
    { word: "DUBLIN",       hint: "Írország fővárosa" },
    { word: "EDINBURGH",    hint: "Skócia fővárosa" },
    { word: "KRAKKÓ",       hint: "Lengyel kulturális főváros" },
    { word: "BUKAREST",     hint: "Románia fővárosa" },
    { word: "BELGRÁD",      hint: "Szerbia fővárosa" },
    { word: "ZAGREB",       hint: "Horvátország fővárosa" },
    { word: "TALLIN",       hint: "Észtország fővárosa" },
    { word: "VILNIUS",      hint: "Litvánia fővárosa" },
    { word: "SZÖUL",        hint: "Dél-Korea fővárosa" },
    { word: "MELBOURNE",    hint: "Ausztrália második legnagyobb városa" },
  ],
  sport: [
    { word: "TRIATLON",      hint: "Úszás, kerékpár, futás egyszerre" },
    { word: "BIATLON",       hint: "Sífutás és lövészet kombinálva" },
    { word: "SZINKRONÚSZÁS", hint: "Vízben koordinált táncos úszás" },
    { word: "EJTŐERNYŐZÉS",  hint: "Repülőből ugrás ejtőernyővel" },
    { word: "HEGYMÁSZÁS",    hint: "Hegycsúcsok meghódítása" },
    { word: "SZIKLAMÁSZÁS",  hint: "Sziklafalakon kapaszkodás" },
    { word: "VITORLÁZÁS",    hint: "Szélerővel hajtott vízijármű" },
    { word: "RAFTING",       hint: "Folyami gyorsasági csónakazás" },
    { word: "BÚVÁRKODÁS",    hint: "Víz alatti úszás oxigénpalackkal" },
    { word: "HŐLÉGBALLON",   hint: "Tüzelt léggömbös repülés" },
    { word: "BUNGEE JUMPING",hint: "Rugalmas kötéllel ugrás mélybe" },
    { word: "VITORLÁZÓREPÜLÉS",hint: "Motor nélküli repülőgéppel szállás" },
    { word: "JÉGKORONG",     hint: "Jégen játszott hokijáték" },
    { word: "LACROSSE",      hint: "Hálós bottal labdás csapatsport" },
    { word: "SQUASH",        hint: "Falra ütik a labdát zárt pályán" },
    { word: "PADEL",         hint: "Üvegfalas teniszszerű sport" },
    { word: "FLOORBALL",     hint: "Teremhoki műanyag bottal" },
    { word: "TAEKWONDO",     hint: "Koreai rúgós harcművészet" },
    { word: "CAPOEIRA",      hint: "Brazil táncos harcművészet" },
    { word: "AIKIDO",        hint: "Japán védelmi harcművészet" },
    { word: "KENDO",         hint: "Japán bambuszkarddal vívás" },
    { word: "MOTOCROSS",     hint: "Terepjáró motoros verseny" },
    { word: "FORMA EGY",     hint: "Leggyorsabb autóverseny sorozat" },
    { word: "POLO",          hint: "Lovon játszott ütős labdajáték" },
    { word: "RITMIKUS GIMNASZTIKA",hint: "Labdával szalaggal torna" },
    { word: "TÍZPRÓBA",      hint: "Tíz atlétikai szám kombinációja" },
    { word: "ÖTTUSA",        hint: "Öt sportágból álló olimpiai verseny" },
    { word: "SÚLYLÖKÉS",     hint: "Nehéz golyót messzire lök" },
    { word: "DISZKOSZVETÉS", hint: "Lapos korongot messzire dob" },
    { word: "GERELYHAJÍTÁS", hint: "Hosszú lándzsát messzire dob" },
  ],
  termeszet: [
    { word: "GLECCSER",      hint: "Lassan mozgó jégtömeg" },
    { word: "FJORD",         hint: "Norvég sziklás öböl" },
    { word: "ATOLL",         hint: "Korallzátony gyűrű a tengeren" },
    { word: "MANGROVE",      hint: "Tengerparti trópusi erdő" },
    { word: "SZAVANNA",      hint: "Afrikai füves puszta" },
    { word: "TAJGA",         hint: "Hideg tűlevelű erdő" },
    { word: "TUNDRA",        hint: "Sarkvidéki növénytelen terület" },
    { word: "KORALLZÁTONY",  hint: "Tengerben élő mészkő alakulat" },
    { word: "STALAKTIT",     hint: "Barlangban lelógó mészkő" },
    { word: "STALAGMIT",     hint: "Barlangban felfelé növő mészkő" },
    { word: "GEJZÍR",        hint: "Periodikusan forró vizet szór" },
    { word: "FENNSÍK",       hint: "Magas, lapos terület" },
    { word: "HORDALÉK",      hint: "Folyó által szállított anyag" },
    { word: "HOMOKDŰNE",     hint: "Szélfútta homokdombok" },
    { word: "ÁRVÍZ",         hint: "Folyó kilépése a medréből" },
    { word: "ASZÁLY",        hint: "Hosszantartó csapadékhiány" },
    { word: "CUNAMI",        hint: "Óriási tengeri hullám" },
    { word: "AURORA",        hint: "Sarki fény az éjszakai égen" },
    { word: "MAGNETIZMUS",   hint: "Vasra ható természeti erő" },
    { word: "GRAVITÁCIÓ",    hint: "Tömegeket vonzó erő" },
    { word: "SZÉN-DIOXID",   hint: "Növények elnyelik, CO2" },
    { word: "ÓZONRÉTEG",     hint: "Légkör UV-védő rétege" },
    { word: "KŐOLAJ",        hint: "Földből termelt tüzelőanyag" },
    { word: "GYÉMÁNT",       hint: "A legkeményebb ásvány" },
    { word: "SMARAGD",       hint: "Zöld drágakő" },
    { word: "ZAFÍR",         hint: "Kék drágakő" },
    { word: "RUBIN",         hint: "Piros drágakő" },
    { word: "PLATINA",       hint: "Legritkább nemesfém" },
    { word: "HIGANY",        hint: "Folyékony fém szobahőn" },
    { word: "SZIKLATÖMB",    hint: "Nagy szabad kőzet" },
  ],
  targyak: [
    { word: "MIKROSZKÓP",    hint: "Apró dolgokat mutat nagyítva" },
    { word: "TÁVCSŐ",        hint: "Messze lévő dolgokat mutat" },
    { word: "SZEXTÁNS",      hint: "Hajósok navigációs eszköze" },
    { word: "BAROMÉTER",     hint: "Légnyomást mérő eszköz" },
    { word: "SZTETOSZKÓP",   hint: "Orvosok szívhang-hallgatója" },
    { word: "VÉRNYOMÁSMÉRŐ", hint: "Vérnyomást mérő eszköz" },
    { word: "METRONÓM",      hint: "Zenészek ritmusjelzője" },
    { word: "ABAKUSZ",       hint: "Régi számolóeszköz golyókkal" },
    { word: "PROJEKTOR",     hint: "Képet falra vetít" },
    { word: "SZKENNER",      hint: "Papírt digitalizál" },
    { word: "PENDRIVE",      hint: "USB-s adattároló" },
    { word: "PROCESSZOR",    hint: "Számítógép agya" },
    { word: "ALAPLAP",       hint: "Számítógép fő áramköri lapja" },
    { word: "VIDEOKÁRTYA",   hint: "Grafikai feldolgozó egység" },
    { word: "ANTENNA",       hint: "Rádió vagy tévéjel fogadó" },
    { word: "TÁVIRÁNYÍTÓ",   hint: "Tévét és elektronikát irányít" },
    { word: "ENCIKLOPÉDIA",  hint: "Mindent tartalmazó ismeretgyűjtemény" },
    { word: "GLOBUSZ",       hint: "Gömb alakú Föld modell" },
    { word: "CSAVARKULCS",   hint: "Csavaranyát húz meg" },
    { word: "SZINTEZŐ",      hint: "Vízszintes síkot ellenőriz" },
    { word: "MÉRŐSZALAG",    hint: "Hosszt mér rugalmas szalaggal" },
    { word: "FESTÉKHENGER",  hint: "Falat fest egyenletesen" },
    { word: "TŰZŐGÉP",       hint: "Papírokat összetűz" },
    { word: "LYUKASZTÓ",     hint: "Papíron lyukat üt" },
    { word: "KRONOMÉTER",    hint: "Rendkívül pontos óra" },
    { word: "NAPÓRA",        hint: "Árnyékkal mutató idő jelző" },
    { word: "PERISKÓP",      hint: "Tengeralattjáró megfigyelő eszköze" },
    { word: "SZÖGMÉRŐ",      hint: "Szögeket mér fokban" },
    { word: "HOMOKÓRA",      hint: "Homok áramlásával méri az időt" },
    { word: "IRÁNYTŰ",       hint: "Mindig észak felé mutat" },
  ],
};

// NEHÉZ szavak — ritka, összetett, hosszú
const WORDS_HARD = {
  allatok: [
    { word: "AXOLOTL",       hint: "Mexikói lárvaállapotban maradó szalamandra" },
    { word: "KACSACSŐRŰ",    hint: "Tojást tojó mérgező sarkú emlős" },
    { word: "ECHIDNA",       hint: "Tüskés tojást tojó emlős" },
    { word: "ROZSOMÁK",      hint: "Erős nagy menyétféle, Arktisz" },
    { word: "ARMADILLÓ",     hint: "Páncélos gömbölyödő emlős" },
    { word: "OPOSSZON",      hint: "Halottnak tetteti magát, erszényes" },
    { word: "VOMBAT",        hint: "Ausztrál erszényes, gödröt ás" },
    { word: "DUGONG",        hint: "Tengeri tehén, füveket eszik" },
    { word: "TAZMÁNIAI ÖRDÖG",hint: "Kis ausztrál erszényes ragadozó" },
    { word: "KVOKKA",        hint: "Mosolygós apró ausztrál erszényes" },
    { word: "NAUTILUSZ",     hint: "Spirálházas mélytengeri puhatestű" },
    { word: "AMMONITES",     hint: "Kihalt spirálházas tengeri állat" },
    { word: "KOELACANTH",    hint: "Élő fosszília, mélytengeri hal" },
    { word: "SZÖRNYHAL",     hint: "Mélytengeri fénylő nyúlvány" },
    { word: "ÖRDÖGHAL",      hint: "Óriás tengeri rája" },
    { word: "SZARVASBÉKA",   hint: "Erdőkben élő erdei béka" },
    { word: "GOLIÁT BÉKA",   hint: "A világ legnagyobb békája" },
    { word: "KÍNAI ÓRIÁSGŐTE",hint: "A világ legnagyobb kétéltűje" },
    { word: "TÜSKÉSBORZ",    hint: "Hegyes tüskéjű kispáncélos" },
    { word: "SZAIGA",        hint: "Orrmányos orrú közép-ázsiai antilop" },
    { word: "OKAPI",         hint: "Zebra csíkos lábú zsiráf rokon" },
    { word: "FOSSA",         hint: "Madagaszkár legnagyobb ragadozója" },
    { word: "BINTURONG",     hint: "Pókmaci, pattogatott kukoricát szagol" },
    { word: "SZARVASLEGUÁN", hint: "Szarvszerű nyúlványos iguana" },
    { word: "HOLOBIONT",     hint: "Szimbiózisban élő szervezetegyüttes" },
    { word: "TUBEWORM",      hint: "Mélytengeri hidrotermális férgek" },
    { word: "TARDIGRÁD",     hint: "Vízimaci, extrém körülményt túlél" },
    { word: "BLOBHAL",       hint: "Mélytengeri szomorú arcú hal" },
    { word: "TAPETUM",       hint: "Macskák szemében visszaverő réteg" },
    { word: "PANGOLIN",      hint: "Pikkelyes hangyász, legnagyobb csempészett állat" },
  ],
  etelek: [
    { word: "KÜRTŐSKALÁCS",    hint: "Magyar édesség, rúdra tekerve sütik" },
    { word: "KANELBULLAR",     hint: "Svéd fahéjas csiga" },
    { word: "SMÖRGÅSBORD",     hint: "Svéd büféasztal hagyomány" },
    { word: "GRAVLAX",         hint: "Skandináv sózott lazac" },
    { word: "SOMLÓI GALUSKA",  hint: "Magyar desszert rummal tejszínnel" },
    { word: "DOBOSTORTA",      hint: "Magyar torta karamellel" },
    { word: "TÖLTÖTT KÁPOSZTA",hint: "Magyar húsos káposztaleveles étel" },
    { word: "BOBOTIE",         hint: "Dél-afrikai fűszeres darált hús" },
    { word: "INJERA",          hint: "Etióp savanyú lepény" },
    { word: "JOLLOF RIZS",     hint: "Nyugat-afrikai fűszeres rizs" },
    { word: "BULGOGI",         hint: "Koreai pácolt grillezett marhahús" },
    { word: "TAKOYAKI",        hint: "Japán polipgömböc" },
    { word: "CHIMICHURRI",     hint: "Argentin petrezselymes szósz" },
    { word: "AÇAÍ",            hint: "Brazil lila bogyós smoothie tál" },
    { word: "KANAFEH",         hint: "Közel-keleti sajtos édes sütemény" },
    { word: "MOLE NEGRO",      hint: "Mexikói kakaós csilis szósz" },
    { word: "HAKARL",          hint: "Izlandi fermentált cápa" },
    { word: "SURSTRÖMMING",    hint: "Svéd savanyított hering, erős szag" },
    { word: "BALUT",           hint: "Fülöp-szigeteki főtt embrionált tojás" },
    { word: "FUGU",            hint: "Japán mérgező hal, veszélyes" },
    { word: "DURIAN",          hint: "Délkelet-ázsiai büdös gyümölcs" },
    { word: "NATTO",           hint: "Japán fermentált szójabab" },
    { word: "CENTURY EGG",     hint: "Kínai fermentált százéves tojás" },
    { word: "CASU MARZU",      hint: "Szardíniai kukacok által fermentált sajt" },
    { word: "ESCAMOLES",       hint: "Mexikói hangyapete étel" },
    { word: "WITCHETTY GRUB",  hint: "Ausztrál Aboriginal fehér lárva" },
    { word: "HÁKARL",          hint: "Izlandi rothasztott cápa" },
    { word: "LUTEFISK",        hint: "Skandináv lúgos vízben áztatott hal" },
    { word: "ÉPOISSES",        hint: "Francia erős illatú mosott sajt" },
    { word: "MARMITE",         hint: "Brit erős sörélesztős kenhető krém" },
  ],
  varosok: [
    { word: "OUAGADOUGOU",  hint: "Burkina Faso fővárosa" },
    { word: "ULAANBAATAR",  hint: "Mongólia fővárosa" },
    { word: "ANTANANARIVO", hint: "Madagaszkár fővárosa" },
    { word: "YAMOUSSOUKRO", hint: "Elefántcsontpart hivatalos fővárosa" },
    { word: "NDJAMENA",     hint: "Csád fővárosa" },
    { word: "BANGUI",       hint: "Közép-afrikai Köztársaság fővárosa" },
    { word: "BRAZZAVILLE",  hint: "Kongói Köztársaság fővárosa" },
    { word: "KINSHASA",     hint: "Kongói Demokratikus Köztársaság fővárosa" },
    { word: "LIBREVILLE",   hint: "Gabon fővárosa" },
    { word: "MALABO",       hint: "Egyenlítői-Guinea fővárosa" },
    { word: "DUSHANBE",     hint: "Tádzsikisztán fővárosa" },
    { word: "ASHGABAT",     hint: "Türkmenisztán fővárosa" },
    { word: "BISHKEK",      hint: "Kirgizisztán fővárosa" },
    { word: "TASHKENT",     hint: "Üzbegisztán fővárosa" },
    { word: "NUKUALOFA",    hint: "Tonga fővárosa" },
    { word: "FUNAFUTI",     hint: "Tuvalu fővárosa" },
    { word: "PALIKIR",      hint: "Mikronézia fővárosa" },
    { word: "YAREN",        hint: "Nauru kerületi székhelye" },
    { word: "MAJURO",       hint: "Marshall-szigetek fővárosa" },
    { word: "SUVA",         hint: "Fidzsi fővárosa" },
    { word: "HONIARA",      hint: "Salamon-szigetek fővárosa" },
    { word: "VAIAKU",       hint: "Tuvalu névleges fővárosa" },
    { word: "APIA",         hint: "Szamoa fővárosa" },
    { word: "NGERULMUD",    hint: "Palau fővárosa" },
    { word: "PORTO-NOVO",   hint: "Benin alkotmányos fővárosa" },
    { word: "VADUZ",        hint: "Liechtenstein fővárosa" },
    { word: "SAN MARINO",   hint: "San Marino fővárosa" },
    { word: "ANDORRA LA VELLA",hint: "Andorra fővárosa" },
    { word: "VALLETTA",     hint: "Málta fővárosa" },
    { word: "PODGORICA",    hint: "Montenegró fővárosa" },
  ],
  sport: [
    { word: "SEPAKTAKRAW",   hint: "Délkelet-ázsiai lábtenisz" },
    { word: "KABADDI",       hint: "Dél-ázsiai légzéses érintős sport" },
    { word: "HURLING",       hint: "Ír bottal labdás csapatsport" },
    { word: "GAELIC FOCI",   hint: "Ír kézzel és lábbal játszott foci" },
    { word: "SHINTY",        hint: "Skót bottal labdás téli sport" },
    { word: "PELOTA",        hint: "Baszk kézzel falon ütött labdajáték" },
    { word: "PATO",          hint: "Argentin lovon játszott kosárlabda" },
    { word: "BUZKASHI",      hint: "Közép-ázsiai lovon játszott küzdőjáték" },
    { word: "SUMO",          hint: "Japán harcisport, nehezebb nyer" },
    { word: "WUSHU",         hint: "Kínai harcművészet, sportváltozat" },
    { word: "SAMBO",         hint: "Szovjet küzdőmúvészeti rendszer" },
    { word: "KRAV MAGA",     hint: "Izraeli katonai önvédelmi technika" },
    { word: "SYSTEMA",       hint: "Orosz katonai harcrendszer" },
    { word: "SILAMBAM",      hint: "Indiai botforgatásos harcművészet" },
    { word: "PENCAK SILAT",  hint: "Maláj indonéz harcművészet" },
    { word: "MUAY THAI",     hint: "Thai nyolc végtagos harcművészet" },
    { word: "BOKATOR",       hint: "Kambodzsai ősi harcművészet" },
    { word: "VOVINAM",       hint: "Vietnami harcművészet" },
    { word: "ESCRIMA",       hint: "Fülöp-szigeteki bottal karddal harc" },
    { word: "CAPOEIRA",      hint: "Brazil táncos harcművészet, zene" },
    { word: "LETHWEI",       hint: "Mianmari fejjel is ütős harc" },
    { word: "FREESTYLE SKI", hint: "Szabadfogású sísportág" },
    { word: "KITESURF",      hint: "Sárkánnyal vontatott szörfözés" },
    { word: "WAKEBOARD",     hint: "Csónakkal vontatott deszkás sport" },
    { word: "SLACKLINING",   hint: "Laza kötélen egyensúlyozás" },
    { word: "HIGHLINING",    hint: "Magasban feszített kötélen járás" },
    { word: "WINGSUIT",      hint: "Szárnyöltözettel repülés sziklák közt" },
    { word: "ZORBING",       hint: "Átlátszó golyóban gurulás" },
    { word: "CHESS BOXING",  hint: "Sakkozás és boksz felváltva" },
    { word: "UNDERWATER HOCKEY",hint: "Víz alatti jégkorong változat" },
  ],
  termeszet: [
    { word: "SZUPERCELLA",   hint: "Tornádót szülő óriási viharfelhő" },
    { word: "MEZOSZIKLÓN",   hint: "Forgó viharfelhő mag" },
    { word: "MAMMATUS",      hint: "Erszényszerű lógó felhőképződmény" },
    { word: "LENTICULÁRIS",  hint: "Lencsealakú felhő hegycsúcsokon" },
    { word: "NOCTILUCENS",   hint: "Éjszaka fénylő magasfelhők" },
    { word: "PIROKLASZT",    hint: "Vulkáni robbanásos omlásos áramlat" },
    { word: "IGNIMBRIT",     hint: "Hőfelhő lerakódásából keletkező kőzet" },
    { word: "OBSIDIÁN",      hint: "Vulkáni üveg, fekete szikla" },
    { word: "PUMICE",        hint: "Könnyű porózus vulkáni kőzet" },
    { word: "SZUBDUKCÍÓ",    hint: "Kéreglemez más alá csúszása" },
    { word: "RIFTZONE",      hint: "Kéreglemezek szétválási zónája" },
    { word: "HOTSPOT",       hint: "Kéreglemez alatti vulkáni folt" },
    { word: "KALDÉRA",       hint: "Vulkán tetején keletkező nagy kráter" },
    { word: "ATOLLKÉPZÉS",   hint: "Süllyedő vulkáni sziget köré növő korall" },
    { word: "TERMOKLÍN",     hint: "Tengerben hőmérsékleti határréteg" },
    { word: "HALIKLIN",      hint: "Tengerben sótartalom-változási réteg" },
    { word: "PIKNOKLINIKA",  hint: "Tengerben sűrűség-változási réteg" },
    { word: "UPWELLING",     hint: "Mélytengeri hideg víz felszínre törése" },
    { word: "THERMOHALINE",  hint: "Sótartalom-hőmérséklet hajtotta óceáni áramlás" },
    { word: "BIOLUMINESZCENS",hint: "Élőlények által kibocsátott fény" },
    { word: "CHEMOSZINTÉZIS", hint: "Kémiai energiából szénhidrát előállítás" },
    { word: "FOTOSZINTÉZIS",  hint: "Napfényből cukor előállítása" },
    { word: "NITROGÉNKÖR",   hint: "Nitrogén körforgása a természetben" },
    { word: "SZÉNKÖR",       hint: "Szén körforgása a természetben" },
    { word: "EUTROFIZÁCIÓ",  hint: "Vizek tápanyagdússágból eredő elalgásodása" },
    { word: "DESZERTIFIKÁCIÓ",hint: "Termőföld sivataggá válása" },
    { word: "PERMAFROST",    hint: "Állandóan fagyott talajréteg" },
    { word: "CRYOKONIT",     hint: "Gleccseren lévő sötét porszemcse" },
    { word: "ABLATION",      hint: "Gleccser tömegvesztesége olvadásból" },
    { word: "MORAINE",       hint: "Gleccser által lerakott kőzettörmelék" },
  ],
  targyak: [
    { word: "SPEKTROMÉTER",  hint: "Fény hullámhosszát mér" },
    { word: "INTERFEROMÉTER",hint: "Fényhullámok interferenciáját mér" },
    { word: "KALORIMETRO",   hint: "Hőmennyiséget mérő eszköz" },
    { word: "ELEKTROMÉTER",  hint: "Elektromos töltést mér" },
    { word: "GALVANOMÉTER",  hint: "Kis áramokat mér" },
    { word: "OSZCILOSZKÓP",  hint: "Elektromos jelek hullámformáit mutatja" },
    { word: "MULTIMÉTERO",   hint: "Többféle elektromos mennyiséget mér" },
    { word: "SZOLARIMÉTERO", hint: "Napsugárzást mérő műszer" },
    { word: "ANEMOMÉTER",    hint: "Szélsebességet mérő műszer" },
    { word: "HIGYROMÉTER",   hint: "Páratartalmat mérő eszköz" },
    { word: "TURBIDIMÉTERO", hint: "Folyadék zavarosságát mérő eszköz" },
    { word: "TACHOMÉTER",    hint: "Forgásszámot mérő eszköz" },
    { word: "REOMÉTER",      hint: "Anyagok folyási tulajdonságait mér" },
    { word: "VISZKOZIMÉTER", hint: "Folyadékok viszkozitását méri" },
    { word: "REFRAKTOMÉTER", hint: "Törésmutatót mérő optikai eszköz" },
    { word: "POLARIMÉTERO",  hint: "Fény polarizációját mérő eszköz" },
    { word: "KROMATOGRÁF",   hint: "Anyagkeverékeket szétválasztó eszköz" },
    { word: "CENTRIFUGA",    hint: "Forgó elválasztó laboratóriumi eszköz" },
    { word: "AUTOKLÁVÉZ",    hint: "Gőznyomásos sterilizáló berendezés" },
    { word: "DESZTILLÁLÓ",   hint: "Folyadékot párologtatva tisztít" },
    { word: "SZUBLIMÁTOR",   hint: "Szilárdból gőzzé alakít hevítve" },
    { word: "LIOFILIZÁTOR",  hint: "Fagyasztva szárító berendezés" },
    { word: "ELEKTROFORÉZIS",hint: "Töltött molekulákat szétválaszt" },
    { word: "SZEKVENCIÁTOR", hint: "DNS sorrendet meghatározó gép" },
    { word: "PCR GÉPEK",     hint: "DNS sokszorosító termikus ciklusos gép" },
    { word: "MIKROTÓM",      hint: "Vékony metszeteket készítő eszköz" },
    { word: "ULTRAHANG",     hint: "Képalkotó diagnosztikai eszköz" },
    { word: "MRI SZKENNER",  hint: "Mágneses rezonanciás képalkotó" },
    { word: "POZITRONTOMOGRÁF",hint: "PET szkenner, anyagcserét mutat" },
    { word: "HADRONGYORSÍTÓ",hint: "Részecskéket nagy sebességre gyorsít" },
  ],
};

const MAX_WRONG = 6;

// Szavak lekérése nehézség és kategória alapján
function getWords(difficulty, category) {
  if (difficulty === 'easy')   return WORDS_EASY[category]   || [];
  if (difficulty === 'medium') return WORDS_MEDIUM[category] || [];
  if (difficulty === 'hard')   return WORDS_HARD[category]   || [];
  return [];
}
