import re

with open('data.js', 'r', encoding='utf-8') as f:
    content = f.read()

new_easy = """const WORDS_EASY = {
  allatok: [
    {word:"KUTYA",hint:"Háziállat, az ember legjobb barátja"},
    {word:"MACSKA",hint:"Doromboló háziállat"},
    {word:"LÓ",hint:"Nagy állat, lovagolnak rajta"},
    {word:"TEHÉN",hint:"Tejet ad, réten legel"},
    {word:"DISZNÓ",hint:"Röfög, rózsaszín"},
    {word:"CSIRKE",hint:"Kotkodál, tojást tojik"},
    {word:"KACSA",hint:"Hápog, vízben úszik"},
    {word:"NYÚL",hint:"Hosszú fülű, ugráló állat"},
    {word:"EGÉR",hint:"Kis rágcsáló"},
    {word:"BÉKA",hint:"Brekeg, vízben él"},
    {word:"MEDVE",hint:"Nagy barna állat, télen alszik"},
    {word:"FARKAS",hint:"Falkában vadász, üvölt"},
    {word:"RÓKA",hint:"Vörös ravasz állat"},
    {word:"OROSZLÁN",hint:"Az afrikai szavanna királya"},
    {word:"TIGRIS",hint:"Csíkos nagymacska"},
    {word:"ELEFÁNT",hint:"Nagy állat, hosszú ormány"},
    {word:"ZSIRÁF",hint:"Leghosszabb nyakú állat"},
    {word:"MAJOM",hint:"Fán lakó állat"},
    {word:"PINGVIN",hint:"Fekete-fehér, nem repül"},
    {word:"DELFIN",hint:"Okos tengeri állat"},
    {word:"CÁPA",hint:"Félelmetes tengeri ragadozó"},
    {word:"KÍGYÓ",hint:"Lábatlan csúszó hüllő"},
    {word:"TEKNŐS",hint:"Páncélos lassan mozgó állat"},
    {word:"BAGOLY",hint:"Éjszakai madár"},
    {word:"PAPAGÁJ",hint:"Trópusi madár, utánoz"},
    {word:"STRUCC",hint:"Legnagyobb madár, nem repül"},
    {word:"KROKODIL",hint:"Veszélyes folyami hüllő"},
    {word:"GEPÁRD",hint:"A leggyorsabb szárazföldi állat"},
    {word:"SZARVAS",hint:"Agancsot visel, erdőben él"},
    {word:"BÁRÁNY",hint:"Kis fehér gyapjas állat"},
    {word:"KECSKE",hint:"Szarvai vannak, mekeg"},
    {word:"BIKA",hint:"Hím tehén, erős"},
    {word:"TYÚK",hint:"Tojást tojik"},
    {word:"KAKAS",hint:"Hajnalban kukorékol"},
    {word:"LIBA",hint:"Fehér nagy szárnyasállat"},
    {word:"GALAMB",hint:"Szürke városi madár"},
    {word:"VERÉB",hint:"Kis barna városi madár"},
    {word:"HATTYÚ",hint:"Fehér elegáns vízimadár"},
    {word:"MÓKUS",hint:"Fán él, diót gyűjt"},
    {word:"SÜN",hint:"Tüskés kis állat"},
    {word:"CSIGA",hint:"Házat hord a hátán"},
    {word:"HANGYA",hint:"Kis rovar, kolóniában él"},
    {word:"MÉHECSKE",hint:"Mézet készít, szúr"},
    {word:"PILLANGÓ",hint:"Színes szárnyú rovar"},
    {word:"BOGÁR",hint:"Hat lábú rovar"},
    {word:"PÓK",hint:"Nyolc lábú, hálót sző"},
    {word:"KUTYA",hint:"Az ember legjobb barátja"},
    {word:"LÓ",hint:"Hátán lovagolnak"},
    {word:"MALAC",hint:"Kis disznó"},
    {word:"BOCI",hint:"Kis tehén"},
    {word:"GÓLYA",hint:"Fehér-fekete madár"},
  ],
  etelek: [
    {word:"ALMA",hint:"Piros vagy zöld gyümölcs"},
    {word:"KENYÉR",hint:"Mindennapi alapétel"},
    {word:"PIZZA",hint:"Olasz kerek lepény sajttal"},
    {word:"LEVES",hint:"Forró folyékony étel"},
    {word:"SALÁTA",hint:"Nyers zöldségek keveréke"},
    {word:"FAGYLALT",hint:"Fagyasztott édes desszert"},
    {word:"TORTA",hint:"Születésnapi édes sütemény"},
    {word:"LÁNGOS",hint:"Magyar utcai étel"},
    {word:"GULYÁS",hint:"Magyar fűszeres húsleves"},
    {word:"PALACSINTA",hint:"Vékony tészta lekvárral"},
    {word:"HAMBURGER",hint:"Zsemle között húspogácsa"},
    {word:"KIFLI",hint:"Félhold alakú péksütemény"},
    {word:"KOLBÁSZ",hint:"Fűszeres húsból töltött"},
    {word:"SAJT",hint:"Tejből készült sárga étel"},
    {word:"MÉZ",hint:"Méhek által készített édes"},
    {word:"LEKVÁR",hint:"Főzött gyümölcsből készült kenőcs"},
    {word:"CSOKI",hint:"Kakaóból készült édesség"},
    {word:"SÜTEMÉNY",hint:"Édes sütési termék"},
    {word:"KEKSZ",hint:"Ropogós édes lap"},
    {word:"CHIPS",hint:"Sült burgonyaszelet"},
    {word:"BANÁN",hint:"Sárga görbe gyümölcs"},
    {word:"NARANCS",hint:"Narancssárga citrusféle"},
    {word:"SZŐLŐ",hint:"Kis bogyók fürtben"},
    {word:"EPER",hint:"Piros apró gyümölcs"},
    {word:"BARACK",hint:"Sárga puha nyári gyümölcs"},
    {word:"KÖRTE",hint:"Körtealakú édes gyümölcs"},
    {word:"SZILVA",hint:"Lila kis gyümölcs"},
    {word:"MEGGY",hint:"Savanykás piros gyümölcs"},
    {word:"DINNYE",hint:"Nagy zöld-piros nyári gyümölcs"},
    {word:"ANANÁSZ",hint:"Trópusi tüskés sárga gyümölcs"},
    {word:"RÉPA",hint:"Narancssárga gyökérzöldség"},
    {word:"BURGONYA",hint:"Barna gumós zöldség"},
    {word:"HAGYMA",hint:"Barna héjú csípős zöldség"},
    {word:"PAPRIKA",hint:"Piros vagy zöld zöldség"},
    {word:"PARADICSOM",hint:"Piros kerek zöldség"},
    {word:"UBORKA",hint:"Zöld hosszú friss zöldség"},
    {word:"KUKORICA",hint:"Sárga csöves növény"},
    {word:"BOR",hint:"Szőlőből készült ital"},
    {word:"TEJ",hint:"Fehér folyadék, tehén adja"},
    {word:"VÍZ",hint:"Átlátszó ital, iváshoz kell"},
    {word:"KÁVÉ",hint:"Barna forró reggeli ital"},
    {word:"TEA",hint:"Forró gyógynövényes ital"},
    {word:"KALÁCS",hint:"Édes fonott sütési termék"},
    {word:"POGÁCSA",hint:"Magyar sós kerek sütemény"},
    {word:"RÉTES",hint:"Magyar nyújtott tésztás sütemény"},
    {word:"NUDLI",hint:"Burgonyás tészta gombóc"},
    {word:"GOMBÓC",hint:"Gömbölyű tészta étel"},
    {word:"RÁNTOTTA",hint:"Tojásból készült reggeli"},
    {word:"OMLETT",hint:"Serpenyőben sütött tojás"},
    {word:"ZSÖMLE",hint:"Kerek kis péksütemény"},
    {word:"VAJ",hint:"Tejszínből készült kenőcs"},
  ],
  varosok: [
    {word:"BUDAPEST",hint:"Magyarország fővárosa"},
    {word:"PÁRIZS",hint:"Eiffel-torony városa"},
    {word:"LONDON",hint:"Big Ben, brit főváros"},
    {word:"RÓMA",hint:"Az örök város"},
    {word:"BERLIN",hint:"Németország fővárosa"},
    {word:"BÉCS",hint:"Osztrák főváros"},
    {word:"PRÁGA",hint:"Csehország fővárosa"},
    {word:"MOSZKVA",hint:"Oroszország fővárosa"},
    {word:"TOKIÓ",hint:"Japán fővárosa"},
    {word:"PEKING",hint:"Kína fővárosa"},
    {word:"SYDNEY",hint:"Ausztrália legnagyobb városa"},
    {word:"DEBRECEN",hint:"Magyarország második legnagyobb városa"},
    {word:"PÉCS",hint:"Dél-magyarországi város"},
    {word:"EGER",hint:"Magyar borvidéki város"},
    {word:"GYŐR",hint:"Dunántúli magyar város"},
    {word:"MISKOLC",hint:"Észak-magyarországi város"},
    {word:"ATHÉN",hint:"Görögország fővárosa"},
    {word:"MADRID",hint:"Spanyolország fővárosa"},
    {word:"STOCKHOLM",hint:"Svédország fővárosa"},
    {word:"OSLO",hint:"Norvégia fővárosa"},
    {word:"HELSINKI",hint:"Finnország fővárosa"},
    {word:"DUBLIN",hint:"Írország fővárosa"},
    {word:"VARSÓ",hint:"Lengyelország fővárosa"},
    {word:"BUKAREST",hint:"Románia fővárosa"},
    {word:"SZÓFIA",hint:"Bulgária fővárosa"},
    {word:"BELGRÁD",hint:"Szerbia fővárosa"},
    {word:"ZÁGRÁB",hint:"Horvátország fővárosa"},
    {word:"DELHI",hint:"India fővárosa"},
    {word:"DUBAI",hint:"Felhőkarcolók városa"},
    {word:"NEW YORK",hint:"Az USA legnagyobb városa"},
    {word:"CHICAGO",hint:"A szél városa"},
    {word:"MIAMI",hint:"Floridai tengerparti város"},
    {word:"TORONTO",hint:"Kanada legnagyobb városa"},
    {word:"LIMA",hint:"Peru fővárosa"},
    {word:"KAIRÓ",hint:"Egyiptom fővárosa"},
    {word:"LAGOS",hint:"Nigéria legnagyobb városa"},
    {word:"NAIROBI",hint:"Kenya fővárosa"},
    {word:"BANGKOK",hint:"Thaiföld fővárosa"},
    {word:"SZÖUL",hint:"Dél-Korea fővárosa"},
    {word:"SZINGAPÚR",hint:"Városállam Ázsiában"},
    {word:"MÜNCHEN",hint:"Bajor sörfesztivál város"},
    {word:"HAMBURG",hint:"Észak-német kikötőváros"},
    {word:"VELENCE",hint:"Vízen álló olasz város"},
    {word:"FIRENZE",hint:"Reneszánsz olasz város"},
    {word:"BARCELONA",hint:"Spanyol katalán város"},
    {word:"MILÁNÓ",hint:"Olasz divat fővárosa"},
    {word:"LISSZABON",hint:"Portugália fővárosa"},
    {word:"AMSZTERDAM",hint:"Holland főváros, csatornák"},
    {word:"BRÜSSZEL",hint:"Belgium fővárosa"},
    {word:"KOPPENHÁGA",hint:"Dánia fővárosa"},
    {word:"REYKJAVIK",hint:"Izland fővárosa"},
  ],
  sport: [
    {word:"FOCI",hint:"A világ legnépszerűbb sportja"},
    {word:"TENISZ",hint:"Ütővel hálón át játszák"},
    {word:"ÚSZÁS",hint:"Vízben végzett sport"},
    {word:"FUTÁS",hint:"Gyalog gyors mozgás"},
    {word:"GOLF",hint:"Lyukba kell ütni a labdát"},
    {word:"BOKSZ",hint:"Ökölharcot jelent"},
    {word:"TORNA",hint:"Akrobatikus ügyességi sport"},
    {word:"RÖPLABDA",hint:"Háló felett ütik a labdát"},
    {word:"KOSÁRLABDA",hint:"Kosárba kell dobni"},
    {word:"JUDO",hint:"Japán küzdősport"},
    {word:"KARATE",hint:"Japán harcművészet"},
    {word:"EVEZÉS",hint:"Csónakon lapáttal hajtás"},
    {word:"KAJAK",hint:"Evezős vízi sport"},
    {word:"ÍJÁSZAT",hint:"Nyíllal célba lövés"},
    {word:"ATLÉTIKA",hint:"Futás, ugrás, dobás"},
    {word:"KERÉKPÁR",hint:"Két kerekű jármű sportág"},
    {word:"LOVAGLÁS",hint:"Lóháton versenyeznek"},
    {word:"JÉGKORONG",hint:"Jégen játszott hokijáték"},
    {word:"SÍELÉS",hint:"Havon léceken csúszás"},
    {word:"KORCSOLYA",hint:"Jégen pengéken csúszás"},
    {word:"SZÖRFÖZÉS",hint:"Hullámokon deszkán"},
    {word:"DARTS",hint:"Nyilat dobnak céltáblára"},
    {word:"BOWLING",hint:"Golyóval bábokat döntik"},
    {word:"RÖGBI",hint:"Ovális labdás csapatsport"},
    {word:"KÉZILABDA",hint:"Magyar sikersport"},
    {word:"VÍZILABDA",hint:"Vízben játszott labdajáték"},
    {word:"TOLLASLABDA",hint:"Tollasokat ütik hálón át"},
    {word:"BIRKÓZÁS",hint:"Két versenyző küzd"},
    {word:"MARATON",hint:"42 km-es hosszútávfutás"},
    {word:"TRIATLON",hint:"Úszás, kerékpár, futás"},
    {word:"BASEBALL",hint:"Amerikai ütős-labdás sport"},
    {word:"KRIKETT",hint:"Brit ütős-labdás sport"},
    {word:"SNOOKER",hint:"Biliárd változat"},
    {word:"SZUMÓ",hint:"Japán harcisport"},
    {word:"TAEKWONDO",hint:"Koreai rúgós harcművészet"},
    {word:"SQUASH",hint:"Falra ütik a labdát"},
    {word:"FUTSAL",hint:"Teremfoci"},
    {word:"AEROBIK",hint:"Zenés edzésmozgás"},
    {word:"JÓGA",hint:"Indiai nyújtó gyakorlatok"},
    {word:"PILATES",hint:"Törzserősítő edzésforma"},
    {word:"SNOWBOARD",hint:"Hódeszkázás lejtőn"},
    {word:"CURLING",hint:"Jégen köveket csúsztatnak"},
    {word:"PÉTANQUE",hint:"Francia golyózásos sport"},
    {word:"POLO",hint:"Lovon játszott sport"},
    {word:"VÍVÁS",hint:"Kardos párbaj sport"},
    {word:"LÖVÉSZET",hint:"Pisztollyal célba lövés"},
    {word:"MAGASUGRÁS",hint:"Léc felett átugrani"},
    {word:"SÚLYLÖKÉS",hint:"Nehéz golyót messzire lök"},
    {word:"RAFTING",hint:"Folyami csónakazás"},
    {word:"BÚVÁRKODÁS",hint:"Víz alatti úszás"},
  ],
  termeszet: [
    {word:"HEGY",hint:"Magas kiemelkedés"},
    {word:"VÖLGY",hint:"Hegyek közötti mélyedés"},
    {word:"TÓ",hint:"Álló belvíz"},
    {word:"FOLYÓ",hint:"Folyamatosan áramló víz"},
    {word:"TENGER",hint:"Nagy sós vízfelület"},
    {word:"ERDŐ",hint:"Sok fából álló terület"},
    {word:"RÉT",hint:"Füves síkság"},
    {word:"SIVATAG",hint:"Forró, homokos vidék"},
    {word:"VULKÁN",hint:"Tűzhányó, lávát lövell"},
    {word:"SZIGET",hint:"Vízzel körülvett szárazföld"},
    {word:"BARLANG",hint:"Sziklában lévő üreg"},
    {word:"VÍZESÉS",hint:"Szikláról lezúduló víz"},
    {word:"SZIVÁRÁNY",hint:"Eső után színes ív az égen"},
    {word:"VILLÁM",hint:"Viharban elektromos kisülés"},
    {word:"ESŐ",hint:"Vízcseppek esnek az égből"},
    {word:"HÓ",hint:"Fehér téli csapadék"},
    {word:"KÖD",hint:"Sűrű vízpárás levegő"},
    {word:"SZÉL",hint:"Légmozgás"},
    {word:"FELHŐ",hint:"Vízpárából álló képződmény"},
    {word:"HOMOK",hint:"Apró kőzetszemcsék"},
    {word:"KŐ",hint:"Szilárd ásványi anyag"},
    {word:"FA",hint:"Erdőkben élő nagy növény"},
    {word:"VIRÁG",hint:"Szép színes növényi rész"},
    {word:"MOHA",hint:"Sziklán élő puha zöld növény"},
    {word:"GOMBA",hint:"Erdei spórás élőlény"},
    {word:"HOLD",hint:"A Föld természetes kísérője"},
    {word:"NAP",hint:"Csillagunk, fényt és meleget ad"},
    {word:"CSILLAG",hint:"Éjszakai égen fénylő égtest"},
    {word:"TŰZHÁNYÓ",hint:"Lávát lövellő hegy"},
    {word:"GLECCSER",hint:"Lassan mozgó jégtömeg"},
    {word:"SZAVANNA",hint:"Afrikai füves puszta"},
    {word:"DZSUNGEL",hint:"Sűrű trópusi erdő"},
    {word:"PATAK",hint:"Kis folyóvíz"},
    {word:"ÖBÖL",hint:"Szárazföldbe nyúló tengerrész"},
    {word:"FÉLSZIGET",hint:"Három oldalról vízzel övezett föld"},
    {word:"ARANY",hint:"Sárga nemesfém"},
    {word:"EZÜST",hint:"Fehér nemesfém"},
    {word:"GYÉMÁNT",hint:"A legkeményebb ásvány"},
    {word:"RUBINT",hint:"Piros drágakő"},
    {word:"SMARAGD",hint:"Zöld drágakő"},
    {word:"TORNÁDÓ",hint:"Örvénylő szélvihar"},
    {word:"ÁRVÍZ",hint:"Folyó kilép a medréből"},
    {word:"ASZÁLY",hint:"Hosszú száraz időszak"},
    {word:"HARMAT",hint:"Reggeli vízcseppek a füvön"},
    {word:"JÉGESŐ",hint:"Jégszemeket tartalmazó csapadék"},
    {word:"AURORA",hint:"Sarki fény az égen"},
    {word:"HOMOKDŰNE",hint:"Szélfútta homokdombok"},
    {word:"KANYON",hint:"Folyó által kimosott sziklavölgy"},
    {word:"LAGÚNA",hint:"Sekély tengeröböl"},
    {word:"ATOLL",hint:"Korallzátony gyűrű a tengeren"},
    {word:"GEJZÍR",hint:"Forró vizet szóró forrás"},
  ],
  targyak: [
    {word:"SZÉK",hint:"Ülőbútor"},
    {word:"ASZTAL",hint:"Lábas lapos bútor"},
    {word:"ÁGY",hint:"Alvóbútor"},
    {word:"AJTÓ",hint:"Helyiségbe vezető nyílás"},
    {word:"ABLAK",hint:"Falba épített üveges nyílás"},
    {word:"LÁMPA",hint:"Fényt ad"},
    {word:"TÜKÖR",hint:"Visszaveri a képet"},
    {word:"KÖNYV",hint:"Olvasni való lapok"},
    {word:"CERUZA",hint:"Írásra és rajzolásra"},
    {word:"TOLL",hint:"Tintával ír"},
    {word:"RADÍR",hint:"Ceruzát töröl"},
    {word:"OLLÓ",hint:"Két pengéjű vágóeszköz"},
    {word:"RAGASZTÓ",hint:"Tárgyakat egymáshoz rögzít"},
    {word:"KALAPÁCS",hint:"Szöget ver be"},
    {word:"FŰRÉSZ",hint:"Fát vág"},
    {word:"KULCS",hint:"Zárat nyit"},
    {word:"ÓRA",hint:"Időt mutat"},
    {word:"TELEFON",hint:"Kommunikációs eszköz"},
    {word:"KAMERA",hint:"Képeket rögzít"},
    {word:"GITÁR",hint:"Húros hangszer"},
    {word:"ZONGORA",hint:"Billentyűs hangszer"},
    {word:"DOB",hint:"Ütős hangszer"},
    {word:"HEGEDŰ",hint:"Vonós hangszer"},
    {word:"ESERNYŐ",hint:"Eső ellen véd"},
    {word:"TÁSKA",hint:"Dolgokat cipel benne"},
    {word:"CIPŐ",hint:"Lábbeli"},
    {word:"SAPKA",hint:"Fejet melegen tartó"},
    {word:"KESZTYŰ",hint:"Kezet melegen tartó"},
    {word:"SÁLF",hint:"Nyakat melegítő kendő"},
    {word:"KABÁT",hint:"Külső meleg felsőruha"},
    {word:"NADRÁG",hint:"Lábszárat fedő ruhadarab"},
    {word:"PÓLÓ",hint:"Rövid ujjú pamut felső"},
    {word:"SZEMÜVEG",hint:"Látást segítő eszköz"},
    {word:"NYAKLÁNC",hint:"Nyakra viselt ékszer"},
    {word:"GYŰRŰ",hint:"Ujjra húzott ékszer"},
    {word:"TÁRCSA",hint:"Pénzt tároló kis tárca"},
    {word:"BŐRÖND",hint:"Utazáshoz nagy táska"},
    {word:"SÍP",hint:"Kis fúvós hangszer"},
    {word:"TROMBITA",hint:"Réz fúvós hangszer"},
    {word:"IRÁNYTŰ",hint:"Mindig észak felé mutat"},
    {word:"HŐMÉRŐ",hint:"Hőmérsékletet mérő eszköz"},
    {word:"MÉRLEG",hint:"Tömeg mérésére szolgál"},
    {word:"VONALZÓ",hint:"Egyenes vonal húzására"},
    {word:"LAPTOP",hint:"Hordozható számítógép"},
    {word:"TABLET",hint:"Érintős eszköz"},
    {word:"CSAVARKULCS",hint:"Csavaranyát húz meg"},
    {word:"FÚRÓ",hint:"Lyukat fúr"},
    {word:"FOGÓ",hint:"Tárgyakat fog meg"},
    {word:"TÉRKÉP",hint:"Területet ábrázoló rajz"},
    {word:"GLOBUSZ",hint:"Gömb alakú Föld modell"},
  ],
};
"""

# Find and replace WORDS_EASY block
pattern = r'const WORDS_EASY = \{.*?\};(?=\s*\n\s*const WORDS_MEDIUM)'
result = re.sub(pattern, new_easy.rstrip(), content, flags=re.DOTALL)

with open('data.js', 'w', encoding='utf-8') as f:
    f.write(result)

print("Done!")
